### ISSUE TITLE
Upload should have the write mode as parameter

### ISSUE THREAD

**Issue by gemiren** [CloudRail/cloudrail-si-android-sdk#1]
For Dropbox upload will fail with conflicts if the file already exists. Need to be able to set the write mode as provided by Dropbox: add, overwrite, or update.

**Comment by FlorianWendel** [comment]
Thank you for your comment. We'll look into adding this feature. Meanwhile, you might be able to work around it by checking if the file exists with getMetadata and then conditionally delete/upload. You can also rename files with the move command like move("/folder/oldname.pdf", "/folder/newname.pdf") .

**Comment by gemiren** [comment]
Thanks for the suggestions. The workaround doesn't look good since that is not thread safe to do. Since Dropbox API has already taken the responsibility of threading with different write modes, this is a huge drawback to not support write mode for users of your awesome library.

**Comment by FlorianWendel** [comment]
First of all thanks a lot for your positive feedback!

You are right, by having the process take multiple requests, intermediate states could be observed by a concurrent third party that would not occur if it were just one atomic request. We're going to explore if and how we can make this work with all of the cloud services in a uniform manner.

I'd like to hear a bit more about the project you are working on to better understand where you are coming from and what your use case is. If you'd be up for a private conversation or a Skype call, just shoot me an email 👍

**Comment by gemiren** [comment]
I understand you want to have the same interface for all cloud storage at the backend. I am not familiar with the other cloud storage so I am not sure how the deal with the upload. However, I don't think it is good to let upload() fail just because you can not set the write mode to overwrite. There are many use cases people just want to keep the latest copy on the cloud.

I have an app which saves user generated data to their Dropbox folder. I used Dropbox sync API before but the Dropbox sync API was deprecated now. The new Dropbox Android SDK is a monster with 20,000 methods! So your awesome library comes to rescue til the moment upload() is called and failed to overwrite the existing file.

**Comment by FlorianWendel** [comment]
We've discussed your suggestions (both the authentication and the write mode part), and have put their implementation on our agenda for the next release. The new version will likely have the write mode as an additional parameter to the upload/move/copy functions in an abstracted manner. Furthermore, we plan to add login and logout functions for explicit interaction with the authentication. Their usage will be optional to keep it simple. Thanks again for your feedback and stay tuned, if all goes well, the new version should be out this week.

**Comment by gemiren** [comment]
Thanks a lot for making those enhancements. That's going to make this library perfect! Looking forward to the next release.

**Comment by FlorianWendel** [comment]
We've just released a new version, check it out
