### ISSUE TITLE
UnifiedCloudStorage...Cant copy or move cloud files

### ISSUE THREAD

**Issue by hardcorelolo** [CloudRail/cloudrail-si-android-sdk#101]
cloudrail-si-android-sdk/ExampleProjects/UnifiedCloudStorage/app/src/main/java/com/cloudrail/fileviewer/Files.java

Line 534-540

private void copyItem() {

    }

    private void moveItem() {

}

Just noticed there is nothing for copy and move item in this source which renders these options useless and would make the user frustrated onto why they don't work.

Anyone have the code for this? Thanks

**Comment by donpwilson** [comment]
@hardcorelolo 
You are looking at the example project which does not show how to copy or move files. The API itself does include such options. I use:

       service.copy(from_source_id, new_source_id);

       service.move(from_source_id, new_source_id);
             
which work very well. The source ids are the paths to the files as specified in the Cloudrail documentation
