### ISSUE TITLE
Can't relogin to Dropbox

### ISSUE THREAD

**Issue by foobnix** [CloudRail/cloudrail-si-android-sdk#114]
Logout from the Dropbox with error

**dropbox.logout();** 
05-24 05:18:37.210  3870  3901 E DEBUG   : com.cloudrail.si.exceptions.AuthenticationException: {"error_summary": "invalid_access_token/..", "error": {".tag": "invalid_access_token"}}
05-24 05:18:37.210  3870  3901 E DEBUG   : 	at com.cloudrail.si.services.Dropbox.logout(Dropbox.java:1404)

Then method
**dropbox.login()**; not open the web view

method
dropbox.**saveAsString();**
return token

[{"access_token":"A6JEgYC1hnMAAAAAAABN0AyXkXxvi9Vg_ypw1Cygjz74bbL_Y0YSIA72wwpdZvcF"}]|

but this token invalid

**AuthenticationException**

**Comment by PatrickStoklasa** [comment]
The above error message will be thrown in case the token is not valid anymore. So I assume you already revoked it somehow. There are two things you can do in that situation: Either instantiate a new Dropbox object or call the loadAsString("[{}]") method on your existing object.

**Comment by foobnix** [comment]
maybe you should do this (loadAsString("[{}]")) automatically on logout method?

**Comment by foobnix** [comment]
thank you, fixed with

dropbox.loadAsString("[{}]");
dropbox.login();

but you should do this automatically

**Comment by PatrickStoklasa** [comment]
The logout method right now calls the Dropbox API to revoke the access token and when that is successful we clear the token and everything is fine. However, this does not happen when the token is revoked before or the call fails. Maybe you are right and this should be done in either case. I will put this on our list and see when we can get to it but for now, I will consider this closed.
