### ISSUE TITLE
Get quality Facebook Profile Picture URL

### ISSUE THREAD

**Issue by kkrishnan90** [CloudRail/cloudrail-si-android-sdk#15]
Hi, 
How do we get a customised size of profile picture using cloudrail API (Facebook profile) ??

I currently see the getPictureURL() and it returns me with 50x50 sized profile picture.
This makes my imageview pretty blurred due to very low resolution.

**Comment by PatrickStoklasa** [comment]
Hi,

Currently there is only the one way to receive the profile pictures. Since you might not be the only one looking for different sized pictures, we will evaluate if there is a good solution to it. I will come back to you as soon as we took a decision on that.

**Comment by kkrishnan90** [comment]
Sure thanks !

**Comment by PatrickStoklasa** [comment]
Hey,

We just updated to version 2.4.1 which should solve your issue. The getPictureURL() method of Facebook should now return the largest available picture! Please check if it works for you and close the issue if it does.
