### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by Victorgf87** [CloudRail/cloudrail-si-android-sdk#17]
Hello, I am testing your Library for my project. I am trying to create Instagram login, and I get an error: "redirect uri does not match registered redirect URI"
What should I set in the Client? Or how can be the uri specified?
Thank you so much!

**Comment by FlorianWendel** [comment]
Hi, have a look at 

https://docs.cloudrail.com/docs/how-to-get-the-credentials#instagram

If you have any more questions, ask away :)

**Comment by Victorgf87** [comment]
ooooh, I didn't see that documentation, neither the link in the main page of the repository. Thank you very much, it is working now, It seems it will be pretty straightforward from now on. 

I like the architecture of your library, and everything it offers, so thanks and good job :)
