### ISSUE TITLE
Authentication was cancelled on Home button Press

### ISSUE THREAD

**Issue by jontyankit** [CloudRail/cloudrail-si-android-sdk#18]
I logged In with facebook, G+, LinkedIn etc. successfully. But the issue comes whenever on the login window I press Home Button I always get **com.cloudrail.si.exceptions.AuthenticationException: Authentication was cancelled**  exception.

**Comment by FlorianWendel** [comment]
This is intentional so developers can react to users canceling
authentication. You're encouraged to catch this exception and handle it
appropriately.
Am 02.07.2016 17:53 schrieb "jontyankit" <notifications@github.com>:

**Comment by jontyankit** [comment]
But I was not cancelling the authentication. I was just receiving the call. If my account have Two-Step verification then in anyways I have to go to check my message box (if I missed it reading from notification)

**Comment by FlorianWendel** [comment]
Alright, I wasn't aware of that. I'll look into the issue and come back to
you once we've fixed it. Can you work around it by restarting login once
you come back into the app?
Am 02.07.2016 18:51 schrieb "jontyankit" <notifications@github.com>:

**Comment by jontyankit** [comment]
If screen timeout occur then also this error occurs.
According to my knowledge if i again initiate this request user will have to fill his username and password again. I cannot distinguish whether user has actually cancelled the authentication or onPause of Authentication activity called.

**Comment by FlorianWendel** [comment]
We've updated the SDK and the new version should not have the issue anymore. It would be great if you could tell me if it's working for you as well.

**Comment by ankitvuliv** [comment]
Thanks @FlorianWendel now its working fine.

**Comment by jontyankit** [comment]
Thanks @FlorianWendel  now its working fine.
