### ISSUE TITLE
File/Folder exists [New Feature]

### ISSUE THREAD

**Issue by RWarnecke** [CloudRail/cloudrail-si-android-sdk#19]
Can you put a function for the cloud drives to check if the file or folder exists and give back true or false. It was very helpful to synchronize files between the device and the cloud drive.

**Comment by FlorianWendel** [comment]
Hi there, thanks for your suggestion!
We'll discuss adding this feature, for now you could do a getMetadata call wrapped in a try-catch like so:

```java 
boolean exists;
try {
    cs.getMetadata("<path>");
    exists = true;
} catch(com.cloudrail.exceptions.NotFoundException e) {
    exists = false;
}
```

**Comment by RWarnecke** [comment]
Thank you, I will use this workaround until you have add this new feature.

**Comment by ajamil76** [comment]
Aku suka dengan cloudrail

**Comment by PatrickStoklasa** [comment]
We just added a new method "exists" to the CloudStorage interface which lets you do exactly what you requested. You can pass a path and it returns true if there is a file/folder already or false if there is not.
