### ISSUE TITLE
Separate the authentication with API calls

### ISSUE THREAD

**Issue by gemiren** [CloudRail/cloudrail-si-android-sdk#2]
Currently authentication is done by the library implicitly when calling upload or download APIs, users have no control on when to do the authentication check. It will be useful to separate that with the other API calls. This will give more flexibility to users. After passing the authentication during the first run. No more activity context is required to pass to the API initialization so it can be used in services without UI.

**Comment by FlorianWendel** [comment]
You are definitely right, having authentication as a separate method would improve flexibility. On the other hand, it would be one more thing developers have to take care of, so we would probably sacrifice simplicity of use.
If you want to trigger the authentication early you could of course always call one of the get requests and ignore the answer, but I do see that this is a bit hacky.

**Comment by gemiren** [comment]
I totally agree a simple solution is better. However, if it is oversimplified it's usage will be limited. 

Another advantage of separating the authentication is to be able to revoke the token to logout the user account. This is a nice feature missing in current APIs.

**Comment by felixkm** [comment]
Suggestions are now part of the library. Thanks for the valuable feedback.

**Comment by jlelse** [comment]
@felixkm So I have to handle the authentication separately from the upload / download? Because the upload thing worked one time before updating and now doesn't...
And I would also wish better docs and samples of how to store the login credentials or whatever you recommended with "saveAsString()".

**Comment by FlorianWendel** [comment]
Login and logout are strictly optional. Upload has one more parameter with the new version, if you want it to behave like before set it to false as documented. You can save and restore login credentials with saveAsString and loadAsString, e.g. to and from the app storage, a database etc. (see http://developer.android.com/training/basics/data-storage/index.html). Normally you want to load on app startup and save before shutdown. If you still have troubles with the upload function, I'd be happy to hear about the details of what goes wrong.

**Comment by jlelse** [comment]
I set the new variable (it's name was set to "override" right?) to true, because I wanted to implement a backup function with DropBox. But I can refresh as often as I want and retry it a lot of times, the files just don't appear on my DropBox. I can't say for sure it's the lib's fault, but I think so, because the other things I did are the same way I always do file operations.

**Comment by FlorianWendel** [comment]
That's weird, do you get an exception? Is data being uploaded?

**Comment by jlelse** [comment]
I just found out that I get an HTTP Exception with the message "path/conflict/folder/..". What does that mean? What port is being used?
