### ISSUE TITLE
Twitter Authentication Issue

### ISSUE THREAD

**Issue by jlelse** [CloudRail/cloudrail-si-android-sdk#20]
I get the following error when trying the Twitter thing. I tried to call postUpdate() and I'm 100% sure I chose the correct Id and Secret for Twitter.

com.cloudrail.si.exceptions.AuthenticationException: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
at com.cloudrail.si.services.Twitter.postUpdate(Twitter.java:726)

What can I do?

**Comment by PatrickStoklasa** [comment]
Hi jlelse,

Have you tried any other method from Twitter yet? If so, do you get the same error message? If not, could you try and see if the error persists?

I did some small tests and the only way i could reproduce the error so far was by putting invalid credentials. Nonetheless i will try and see if i can reproduce it any other way.

**Comment by PatrickStoklasa** [comment]
Closed due to inactivity.
