### ISSUE TITLE
Http exception

### ISSUE THREAD

**Issue by xbandx68** [CloudRail/cloudrail-si-android-sdk#21]
I would like to upload the database when the use click on button and I have write this function:

```
private void uploadDatabase() {
		final File bckDatabase = BackupDatabase();
		if(bckDatabase != null) {
			startSpinner();
			new Thread(new Runnable() {
				@Override
				public void run() {
					InputStream fs = null;
					long size = -1;
					try {
						//fs = getOwnActivity().getContentResolver().openInputStream(uri);
						//size = getOwnActivity().getContentResolver().openAssetFileDescriptor(uri, "r").getLength();
						// mi ricavo il file e la sua lunghezza
						//File currentDB = new File( MainActivity.DB_PATH+"/"+PreferenceConstants.DB_DATABASE_STORE);
						File currentDB = new File( bckDatabase.getPath());
						size = currentDB.length();
						if (currentDB.exists()) {
							fs = new FileInputStream(currentDB);
						}else{
							MainActivity.this.runOnUiThread(new Runnable() {
								@Override
								public void run() {
									Toast.makeText(getContext(), "Unable to access file!", Toast.LENGTH_SHORT).show();
								}
							});
							return;
						}
					} catch (Exception e) {
						stopSpinner();
						MainActivity.this.runOnUiThread(new Runnable() {
							@Override
							public void run() {
								Toast.makeText(getContext(), "Unable to access file!", Toast.LENGTH_SHORT).show();
							}
						});
						return;
					}

					getService().createFolder("/ordinifornitori");
					getService().upload("/ordinifornitori/google_ordinifornitori.db", fs, size, true); // overwrite if exist

	//				getOwnActivity().runOnUiThread(new Runnable() {
	//					@Override
	//					public void run() {
	//						updateList();
	//					}
	//				});
				}
			}).start();
		}
	}
```

But I receive always Http exception

**Comment by PatrickStoklasa** [comment]
At which line is the HttpException thrown? 'createFolder' or 'upload'? Is there any additional error message presented? Could you maybe post the complete stack trace in order for us to get as much information about the error as possible?

**Comment by xbandx68** [comment]
I think is create folder
```
 Caused by: com.cloudrail.si.exceptions.HttpException
                                                     at com.cloudrail.si.services.GoogleDrive.createFolder(GoogleDrive.java:1055)
                                                     at com.bandweb.ordinifornitori.asynctask.UploadOnCloud.doInBackground(UploadOnCloud.java:67)
                                                     at com.bandweb.ordinifornitori.asynctask.UploadOnCloud.doInBackground(UploadOnCloud.java:21)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:288)
```

**Comment by PatrickStoklasa** [comment]
Does that folder already exist in your drive? Because if it does the SDK will thrown an error. In order to prevent that you have two choices. The easiest but not very reliable solution is to just catch the errors thrown by 'createFolder' and ignore them. This solution has the disadvantage that you can't distinguish if the reason for the error is that the folder is already there or any other cause. 
The second option would be to call 'getMetadata' for the folder you want to check and catch NotFoundExceptions. If such an exception is thrown you can call 'createFolder' in the catch-block. This should be the preferred solution in your case.

If the folder does not yet exist in your case, would you tell me which version of the SDK you are using, in order for us to do further testing?

**Comment by xbandx68** [comment]
Hi, the folder exist, but if I bypass **createFolder(uploadDir)** and use only **upload(uploadDir + FileName, fs, size, true);** I have the same error.
I use Android Studio 2.1.2 and SDK 23 and 24

**Comment by PatrickStoklasa** [comment]
Which version of our library are you using?

**Comment by FlorianWendel** [comment]
Do you add a "/" between uploadDir and FileName?

**Comment by xbandx68** [comment]
yes, the final string is "/ordinifornitori/database.db", I use this version of library
compile 'com.cloudrail:cloudrail-si-android:2.4.2'

**Comment by PatrickStoklasa** [comment]
Could you try to exchange GoogleDrive for Dropbox or one of the others and see if this would work such that we know that this is actually an issue with the integration of GoogleDrive or sth more generic?

**Comment by xbandx68** [comment]
Ok, with DropBox method all works ok!, but with GoogleDrive none!

**Comment by PatrickStoklasa** [comment]
I just got the same error when deactivating the Drive API in the development console of google. Could you follow that link (https://console.developers.google.com/apis/api/drive/overview) and see if it is activated for the project you are trying to use.

**Comment by xbandx68** [comment]
Yes man! I've see your link and therin't activated, I've activated and now works! googledrive and dropbox also.
