### ISSUE TITLE
HttpException cannot be cast...

### ISSUE THREAD

**Issue by xbandx68** [CloudRail/cloudrail-si-android-sdk#23]
Hi , I have updated the library (2.5.4 and compileSdkVersion 24) but now I obtain this error 
java.lang.ClassCastException: com.cloudrail.si.exceptions.HttpException cannot be cast to com.cloudrail.si.types.Error

on this code:
CloudMetaData meta  = Services.getInstance().getService(1).getMetadata("/ordinifornitori");

and the directory exist on cloud dropbox

**Comment by PatrickStoklasa** [comment]
I just saw that we are actually throwing the wrong error, so this will be fixed soon. Nonetheless, that part of the code is only executed if the http request throws an UnknownHostException which is usually issued when you don't have a working internet connection. Could you check if the problem persists with a working internet connection?

**Comment by xbandx68** [comment]
yes I have Internet connection now, but the log is:

Error: java.lang.ClassCastException: com.cloudrail.si.exceptions.HttpException cannot be cast to com.cloudrail.si.types.Error
	at com.cloudrail.si.services.Dropbox.createFolder(Dropbox.java:710)
	at com.bandweb.ordinifornitori.asynctask.UploadOnCloud.doInBackground(UploadOnCloud.java:109)
	at com.bandweb.ordinifornitori.asynctask.UploadOnCloud.doInBackground(UploadOnCloud.java:27)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by PatrickStoklasa** [comment]
Could you go back to the old version again and see if that still works? If not, we will release a fix to get a more meaningful error message soon. It will probably be tomorrow, so i will keep you updated!

**Comment by xbandx68** [comment]
I've tried with 2.4, compiled SDK 24, but same error

**Comment by FlorianWendel** [comment]
Your stack trace says that createFolder throws an exception.

While the class cast exception suggests that exception handling has a bug (which will be fixed), this shouldn't be a problem if there is no exception in the first place.

You've said that the folder exists on Dropbox, are you maybe trying to create an already existing folder? This is indeed expected to throw an exception.

**Comment by xbandx68** [comment]
now works without exceptions.HttpException....do you have found some bugs?

**Comment by PatrickStoklasa** [comment]
Glad it works for you now. With the new update we fixed the error message that was displayed. It should now throw a more meaningful exception in cases of a missing internet connection.
