### ISSUE TITLE
getAllocation.getTotal() got negative value

### ISSUE THREAD

**Issue by sicksand** [CloudRail/cloudrail-si-android-sdk#24]
Hi, 

I am using cloudrail 2.5.4 (android)

the total space i'm getting is in negative

```
SpaceAllocation space = getService().getAllocation();
            int csTotal = (int) (long) space.getTotal();
            Log.d("t", ""+csTotal);
            int csUsed = (int) (long) space.getUsed();
            Log.d("u", ""+csUsed);
            int csAvail = ((int) (long) space.getTotal()) - ((int) (long) space.getUsed());
```
the result 
![screen shot 2016-07-25 at 5 20 39 pm](https://cloud.githubusercontent.com/assets/305408/17096587/a68680a4-528c-11e6-8b98-7cada427e748.png)

How do i get real size of total?

thanks

**Comment by FlorianWendel** [comment]
By not casting it to an int. The total size likely exceeds the maximum number an int can represent and thus overflows to a negative value. Use long instead:

    SpaceAllocation space = getService().getAllocation();
    long csTotal = space.getTotal();
    Log.d("t", ""+csTotal);
    long csUsed = space.getUsed();
    Log.d("u", ""+csUsed);
    long csAvail = csTotal - csUsed;
