### ISSUE TITLE
How to get all files in the root directory

### ISSUE THREAD

**Issue by slidenerd** [CloudRail/cloudrail-si-android-sdk#25]
I would like to get a list of all the files and folders present in the root when it comes to dropbox or other providers.
I tried

List<CloudMetaData> files = mCloudStorage.getChildren("/");
Toast.makeText(CloudRailStorageService.this, files.toString(), Toast.LENGTH_LONG).show();

But nothing shows up on the screen, am I missing something?

Thanks

**Comment by PatrickStoklasa** [comment]
Do you get any error or is it just an empty list? Do you run your code within a different thread? Overall this should be the correct way to go about it though.

**Comment by slidenerd** [comment]
Just an empty list

**Comment by FlorianWendel** [comment]
Are you sure that the root folder contains any files or folders?
It would also be helpful if you could post some more code.

**Comment by PatrickStoklasa** [comment]
Closed due to inactivity.

**Comment by SakilKadri** [comment]
access root folder of dropbox:
NSMutableArray<CRCloudMetaData *> * metas = [self.service childrenOfFolderWithPath:@"/"""];
        NSLog(@"Folder has %@ children", metas);
