### ISSUE TITLE
Limit to list returned from getChildren

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#28]
I have a folder in OneDrive with 214 files. The getChildren function only returned the first 199 of them. I'm not surprised if you have to loop to get the remainder but how do you do this or is this a bug?

**Comment by PatrickStoklasa** [comment]
Indeed, the OneDrive implementation seems to have a bug there. I will fix it and let you know as soon as it is released. Thanks for reporting it!

**Comment by PatrickStoklasa** [comment]
Could you please update to version 2.6.4 and see if the issue is solved.

**Comment by donpwilson** [comment]
I confirm that this issue is solved

**Comment by PatrickStoklasa** [comment]
Glad to hear! This issue will be closed.
