### ISSUE TITLE
HttpException on login to Box

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#29]
I am intermittently getting an HttpException when I try to log in to Box using an implicit login. I show the diagnostic log messages below. The issue is that, despite the exception being thrown, the Box login screen is displayed and you can still log in to Box. My app continues on the assumption that the login failed, for instance by not storing the login credentials. I see two issues. First, any exception thrown should close the web view, etc. Secondly, no error should be thrown because the login screen is displayed.

08-05 11:08:39.868 2101-2975/com.dpw.photomanager V/chromium: external/chromium/net/socket/ssl_client_socket_openssl.cc:310: [0805/110839:INFO:ssl_client_socket_openssl.cc(310)] ssl_ctx_ is used
08-05 11:08:40.828 2101-2975/com.dpw.photomanager V/chromium: external/chromium/net/socket/ssl_client_socket_openssl.cc:508: [0805/110840:INFO:ssl_client_socket_openssl.cc(508)] ~SSLClientSocketOpenSSL()
08-05 11:08:41.899 2101-2101/com.dpw.photomanager D/TilesManager: Starting TG #0, 0x60e21088
08-05 11:08:41.899 2101-2101/com.dpw.photomanager D/TilesManager: new EGLContext from framework: 5afe7de0 
08-05 11:08:41.899 2101-2101/com.dpw.photomanager D/GLWebViewState: Reinit shader
08-05 11:08:41.914 2101-2101/com.dpw.photomanager D/GLWebViewState: Reinit transferQueue
08-05 11:08:43.235 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Broken after finding a focusable Node
08-05 11:08:43.235 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Final Next Nodename = <INPUT>, tagname = <INPUT>
08-05 11:08:43.235 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::previousTextOrSelectNode :  !previousNode )
08-05 11:08:43.235 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Broken after finding a focusable Node
08-05 11:08:43.235 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Final Next Nodename = <INPUT>, tagname = <INPUT>
08-05 11:08:43.235 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::previousTextOrSelectNode :  !previousNode )
08-05 11:08:43.430 2101-2960/com.dpw.photomanager I/GATE: <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
08-05 11:08:43.586 2101-2101/com.dpw.photomanager E/ViewRootImpl: sendUserActionEvent() mView == null
08-05 11:09:00.422 2101-2960/com.dpw.photomanager I/GATE: <GATE-M>DEV_ACTION_ERROR</GATE-M>
08-05 11:09:00.422 2101-2960/com.dpw.photomanager V/webkit: reportError errorCode(-6) desc(Couldn't connect to the server.)
08-05 11:09:00.477 2101-2960/com.dpw.photomanager I/GATE: <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
08-05 11:09:01.000 2101-2101/com.dpw.photomanager V/WebViewInputDispatcher: blockWebkitDraw
08-05 11:09:01.000 2101-2101/com.dpw.photomanager V/WebViewInputDispatcher: blockWebkitDraw lockedfalse
08-05 11:09:01.305 2101-2960/com.dpw.photomanager D/webview: blockWebkitViewMessage= false
08-05 11:09:01.352 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Broken after finding a focusable Node
08-05 11:09:01.352 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Final Next Nodename = <INPUT>, tagname = <INPUT>
08-05 11:09:01.352 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::previousTextOrSelectNode :  !previousNode )
08-05 11:09:01.352 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Broken after finding a focusable Node
08-05 11:09:01.352 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::nextTextOrSelectNode : Final Next Nodename = <INPUT>, tagname = <INPUT>
08-05 11:09:01.352 2101-2960/com.dpw.photomanager D/webcoreglue: WebViewCore::previousTextOrSelectNode :  !previousNode )
08-05 11:09:01.657 2101-2101/com.dpw.photomanager D/WebView: onSizeChanged - w:1024 h:198
08-05 11:09:01.805 2101-2726/com.dpw.photomanager E/PP: error while executing job com.dpw.photoplayer.Activity_Connections$LoginToCloudRailDrive@41fb7698

**Comment by PatrickStoklasa** [comment]
I think the cause of this could be the same as the one you had with Dropbox despite throwing a different error. The thread running the first call is stopped due to the error and the second one continues by displaying the WebView again. It would also be very helpful to get the the whole error message here.

**Comment by donpwilson** [comment]
See my comments for #30

**Comment by donpwilson** [comment]
I've made changes in my app which appear to have cleared this issue.
