### ISSUE TITLE
Why there is a WeatherService in this library?

### ISSUE THREAD

**Issue by gemiren** [CloudRail/cloudrail-si-android-sdk#3]
How come a cloud storage lib needs to implement a WeatherService? I hope that's not used to forecast the "cloud" status. This makes this library feels like a malware considering it handles user accounts which is highly sensitive. Guess I'll have to go back to use the official Dropbox SDK instead of this library, sadly.

**Comment by felixkm** [comment]
Malware? I hope the weather isn't that bad :) CloudRail is designed to support multiple interfaces, so not just cloud storage. We currently work on a social abstraction layer for instance. Weather is in there to demonstrate in which direction we want to go with this library: Multiple unified interfaces for different use cases. We just started with cloud storage. Hope that makes sense and convinces you to use this library anyway. Happy to answer any more question you might have.
