### ISSUE TITLE
RuntimeException in function checkAuthentication at 13

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#30]
I have the above intermittent error when using an implicit login for Dropbox. Is there a way that I can debug it or does it indicate an issue? The log messages preceding it are:

08-05 12:31:48.977 20050-20050/com.dpw.photomanager I/webclipboard: clipservice: android.sec.clipboard.ClipboardExManager@422e4ca8
08-05 12:31:48.977 20050-21021/com.dpw.photomanager V/webkit: BrowserFrame constructor: this=Handler (android.webkit.BrowserFrame) {422cb270}
08-05 12:31:49.024 20050-20050/com.dpw.photomanager D/ProgressBar: setProgress = 0
08-05 12:31:49.024 20050-20050/com.dpw.photomanager D/ProgressBar: setProgress = 0, fromUser = false
08-05 12:31:49.024 20050-20050/com.dpw.photomanager D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 10000
08-05 12:31:49.071 20050-20050/com.dpw.photomanager D/WebView: loadUrlImpl: called
08-05 12:31:49.071 20050-21021/com.dpw.photomanager D/webcore:  CORE loadUrl: called
08-05 12:31:49.071 20050-21021/com.dpw.photomanager D/webkit: Firewall not null
08-05 12:31:49.071 20050-21021/com.dpw.photomanager D/webkit: euler: isUrlBlocked = false
08-05 12:31:49.141 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: left = 0
08-05 12:31:49.141 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: top = 0
08-05 12:31:49.141 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: right = 48
08-05 12:31:49.141 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: bottom = 48
08-05 12:31:49.180 20050-21037/com.dpw.photomanager V/chromium: external/chromium/net/socket/ssl_client_socket_openssl.cc:310: [0805/123149:INFO:ssl_client_socket_openssl.cc(310)] ssl_ctx_ is used
08-05 12:31:49.180 20050-20050/com.dpw.photomanager D/WebView: onSizeChanged - w:1024 h:527
08-05 12:31:49.625 20050-20050/com.dpw.photomanager I/PP: main Activity_Connections : onSaveInstanceState()
08-05 12:31:52.391 20050-20050/com.dpw.photomanager D/WebCore: uiOverrideUrlLoading: shouldOverrideUrlLoading() returnsfalse

This is slightly different from the messages when the login is successful:

08-05 12:52:44.805 20050-20050/com.dpw.photomanager I/webclipboard: clipservice: android.sec.clipboard.ClipboardExManager@42095a60
08-05 12:52:44.907 20050-20050/com.dpw.photomanager D/ProgressBar: setProgress = 0
08-05 12:52:44.907 20050-20050/com.dpw.photomanager D/ProgressBar: setProgress = 0, fromUser = false
08-05 12:52:44.907 20050-20050/com.dpw.photomanager D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 10000
08-05 12:52:45.008 20050-20050/com.dpw.photomanager D/WebView: loadUrlImpl: called
08-05 12:52:45.047 20050-21021/com.dpw.photomanager V/webkit: BrowserFrame constructor: this=Handler (android.webkit.BrowserFrame) {4204f370}
08-05 12:52:45.047 20050-21021/com.dpw.photomanager D/webcore:  CORE loadUrl: called
08-05 12:52:45.047 20050-21021/com.dpw.photomanager D/webkit: Firewall not null
08-05 12:52:45.047 20050-21021/com.dpw.photomanager D/webkit: euler: isUrlBlocked = false
08-05 12:52:45.094 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: left = 0
08-05 12:52:45.094 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: top = 0
08-05 12:52:45.094 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: right = 48
08-05 12:52:45.094 20050-20050/com.dpw.photomanager D/ProgressBar: updateDrawableBounds: bottom = 48
08-05 12:52:45.133 20050-20050/com.dpw.photomanager D/WebView: onSizeChanged - w:1024 h:527
08-05 12:52:45.250 20050-21037/com.dpw.photomanager V/chromium: external/chromium/net/socket/ssl_client_socket_openssl.cc:310: [0805/125245:INFO:ssl_client_socket_openssl.cc(310)] ssl_ctx_ is used
08-05 12:52:45.539 20050-20050/com.dpw.photomanager I/PP: main Activity_Connections : onSaveInstanceState()
08-05 12:52:48.289 20050-20050/com.dpw.photomanager D/WebCore: uiOverrideUrlLoading: shouldOverrideUrlLoading() returnsfalse
08-05 12:52:48.399 20050-20050/com.dpw.photomanager I/PP: main Activity_Connections : onResume() dialog accepted true source 5001
08-05 12:52:50.289 20050-21037/com.dpw.photomanager V/chromium: external/chromium/net/socket/ssl_client_socket_openssl.cc:508: [0805/125250:INFO:ssl_client_socket_openssl.cc(508)] ~SSLClientSocketOpenSSL()

**Comment by PatrickStoklasa** [comment]
No you will probably not be able to debug it yourself. I have seen this issue before and it seems to occur if you are triggering multiple authentication calls at the same time. Meaning that if you do a second call to our interface without the user finishing the authentication process this might conflict with the first call and triggers the authentication process again. I don't know if this applies in your case but it would be helpful if you could provide the stack trace for the error message since this should give us a bit more information to proceed.

**Comment by donpwilson** [comment]
Unfortunately, there appears to be an issue with android-priority-jobqueue which I use to wrap all my internet accessing in that it is not passing the full stack trace back, only the exception itself. I've reported the issue.
Meanwhile, if or when it reappears, I'll try to catch it in debug mode to get more info.

**Comment by donpwilson** [comment]
I've made changes in my app which appear to have cleared this issue.
