### ISSUE TITLE
Add Range Requests support?

### ISSUE THREAD

**Issue by isabsent** [CloudRail/cloudrail-si-android-sdk#35]
Nice library! Thanks! But what about to support [Range Requests](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35)? Code snippet for Dropbox (v.1) may look as 

```
public byte[] getByteRange(long position, int length){
    String downloadUrl = "https://api-content.dropbox.com/1/files/dropbox" + "/path/to/desired/file";
    try {
        URL url = new URL(downloadUrl);
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("GET");
        con.setRequestProperty("Authorization", "Bearer " + DropboxActivity.getAccessToken(service.getSession()));
        con.setRequestProperty("Range", "bytes=" + position + "-" + (position + length - 1));
        InputStream is = con.getInputStream();
        return IOUtils.toByteArray(is);
    } catch (IOException e) {
        e.printStackTrace();
        return null;
    }
}
```

It may be very useful for apps that use encryption (many files in one encrypted file on a cloud) to avoid reading over HTTP of whole encrypted file to decrypt a small file inside of it. I can propose analogous code for other supported clouds if you are interested in.

**Comment by PatrickStoklasa** [comment]
Thanks for your suggestion, we will take a closer look on it and check if it is actually possible with all of the services we integrated. We will get back to you as soon as we took a decision on it.

**Comment by PatrickStoklasa** [comment]
Check out our newest functionality (https://documentation.cloudrail.com/android/android/Usage#advanced-request), you should be able to implement your requested feature with it. Not the perfect solution but you can make it work like that.

**Comment by isabsent** [comment]
Thanks! I will take it into account.
