### ISSUE TITLE
Splitting the release?

### ISSUE THREAD

**Issue by pellyadolfo** [CloudRail/cloudrail-si-android-sdk#36]
I have tried to include CloudRail to my project. Despite FAQs says no overhead, I feel 3 direct impacts:

* My MinSDK must be raised to 15 from my current 11. I understand that if your release includes so many libraries, the MinSDK is the max MinSDK required by all these libraries. As a side effect to have in my code libraries that probably I wont use, this would exclude many target devices from my app.

* Is the first library that requires me to set multiDexEnabled true as probably compilation goes beyond 64k methods. Again, why should I be forced to do that for many libraries I probably will not use.

* The aar adds 500kb to my app.

So, I see the overhead and decided to exclude the library, by now, because it forces me oversizing my app. However I like the idea, so, question: why not making smaller releases? 

(e.g. social-cloudrail.aar, payments-cloudrail.aar, sms-cloudrail.aar.... )

or even by service:

(cloudrail-facebook.aar, cloudrail-twitter.aar...)

so 3 issues above get, at least, reduced.

Thanks

**Comment by PatrickStoklasa** [comment]
Thank you for your feedback! We will check again if the min version of 15 can be reduced without impacting features within the library. If it is not possible we can not reduce the min version any further.

We have investigated the size issue since the library used to be a lot smaller and discovered that there is some stuff we can do to reduce both, the size of the library as well as the method / class count. For now, we do not plan to split it up but with our optimizations it should be a lot better already. I will notify when we release a new version that includes those changes.

**Comment by jlelse** [comment]
I don't really agree with @pellyadolfo 's criticism. Although I think it would be cool to choose which services to add to the app, it's not true that Cloudrail depends on many other libraries. They do everything via direct server calls etc. I think. If you compare this library with Facebooks library (for example), it will still be a lot smaller I think. I can't believe the 500kb.
And you may also want to try Proguard.

**Comment by PatrickStoklasa** [comment]
As an update, the latest release contains the optimizations i mentioned above. We were able to decrease the size by over 200kb. The method / class count should also be way better than before.

**Comment by pellyadolfo** [comment]
sounds very good:

* 2.6.7 -> 564.2k and 2224 methods
* 2.6.8 -> 334k and 1411 methods
(http://www.methodscount.com/)

I seems facebook android API asks for API 15 (ncludes Audience Network, and Facebook packages. Requires Android API 15.)

trying tomorrow...  Thanks

**Comment by PatrickStoklasa** [comment]
We have been able to reduce the minimum SDK version to 10 instead of 15. This should allow you to put yours back to 11 ;-) Despite not splitting up the release as you suggested, we have improved in the areas you were concerned about. Does this solve the issue for now such that we can close it?
