### ISSUE TITLE
storageProvider.createFolder("/TestFolder"); call will not exit

### ISSUE THREAD

**Issue by WksKing** [CloudRail/cloudrail-si-android-sdk#39]
Hi, I want to use cloudrail to call oneDrive, but seems like terrible. I followed the steps to create, and I copied a demo app like below, the method called as title will execute loop by loop, will not exit.
my english is poor, can you help me to try?

`public class MainActivity extends AppCompatActivity {
    private CloudStorage storageProvider;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        CloudRail.setAppKey("57e1e7221814ca203edc06a8");

        storageProvider = getOneDriveStorage();

        new Thread() {
            @Override
            public void run() {
                Log.i("King", "create Folder");
                storageProvider.createFolder("/TestFolder"); // <---
                InputStream stream = null;
                try {
                    AssetManager assetManager = getAssets();
                    stream = assetManager.open("temp.txt");
                    long size = assetManager.openFd("temp.txt").getLength();
                    Log.i("King", "start upload");
                    storageProvider.upload("/TestFolder/temp.txt", stream, size, false); // <---
                    Log.i("King", "upload done");
                } catch (Exception e) {
                    // TODO: handle error
                    e.printStackTrace();
                } finally {
                    // TODO: close stream
                }
            }
        }.start();

    }

    private CloudStorage getOneDriveStorage(){
        CloudStorage cs = new OneDrive(this, "acc94fe4-12e8-4d2b-b564-75e4b80bbd18", "WdpDWRSs85ooBKObyRSfYRn");

        return cs;
    }
}`

btw, when I creating an app in [https://apps.dev.microsoft.com/#/appList](https://apps.dev.microsoft.com/#/appList) I can't set the Redirect URI for mobile application, because it's not editable.

**Comment by FlorianWendel** [comment]
Hi there,

at first glance your code looks alright. Have you followed the instructions at 
https://github.com/CloudRail/cloudrail-si-android-sdk/wiki/Services#onedrive
to set up your OneDrive app?

**Comment by PatrickStoklasa** [comment]
Closed due to inactivity.
