### ISSUE TITLE
Developer Console on CloudRail.com

### ISSUE THREAD

**Issue by jlelse** [CloudRail/cloudrail-si-android-sdk#4]
In your YouTube videos you always use http://workbench.cloudrail.com/. But when I try to access that URL I get redirected to the CloudRail homepage. But how do I now use APIs like Facebook etc.?

**Comment by felixkm** [comment]
That was our mistake, sorry for the confusion. The workbench was part of an older version of CloudRail which is no longer supported. There you had the possibility to add and remove specific services from the SDK. In the meantime we decided to have everything in the SDK by default. So far just Cloud Storage is supported but we work hard to add more interfaces to the library. Social for instance is coming in two weeks. I've just removed the misleading videos, thanks for reaching out. Let me know if you have more questions.

**Comment by jlelse** [comment]
Ok thanks for the reply
