### ISSUE TITLE
FileStorage - GoogleDrive Provider getModifiedAt of CloudMetaData is null

### ISSUE THREAD

**Issue by gandulf** [CloudRail/cloudrail-si-android-sdk#41]
Could it be that modifiedAt is not supported by CloudRail for GoogleDrive, because id i fetch a metadata object for a file it is always null. The some elements of the metadata are there: filename, size, ...

I need to the modifiedAt Date to determine wether the version on the cloud is new than my current local version and then either upload or download it...

**Comment by PatrickStoklasa** [comment]
Hi there,

I just checked it again but it seems to work fine. So if there is a last modified date returned by GoogleDrive, it is extracted correctly. So i would assume that there is no such date returned. For what type of file do you try to read it? Maybe GoogleDrive does not provide it under certain circumstances.

**Comment by PatrickStoklasa** [comment]
Closed due to inactivity.
