### ISSUE TITLE
Facebook profile.getFullName Fatal Exception

### ISSUE THREAD

**Issue by s-nour** [CloudRail/cloudrail-si-android-sdk#45]
Hello there, 
I'm using CloudRail to implement social media log in for an Android application, so far it's been working fine except for Facebook login, the log in process is carried as expected, I'm able to receive the access token, but using attempting to obtain user information such as full name or email address is producing the following exception.

FATAL EXCEPTION: Thread-114215
                                                                   Process: com.uae.uae, PID: 3737
                                                                   com.cloudrail.si.exceptions.HttpException
                                                                       at com.cloudrail.si.services.Facebook.getFullName(Facebook.java:367)
                                                                       at com.uae.uae.activities.LogInActivity$1.run(LogInActivity.java:146)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by PatrickStoklasa** [comment]
Could you maybe post the result of saveAsString() after the login process has taken place (you can of course replace the real access token). I just want to validate that all the necessary information is correctly received such that we know that it is not a configuration issue. 

Which other services are you using for social login?

**Comment by s-nour** [comment]
String data = profile.saveAsString(); 
Log.e("data", data);

This is the result: 
data: [{"accessToken":"----------------------","expireIn":1482136113361}]

**Comment by PatrickStoklasa** [comment]
This looks fine to me... Did you follow our guide for setting up the Facebook App or did you have one already? Maybe you could try to create another one and see if this works. Sometimes there seems to be an issue with the configuration.

**Comment by s-nour** [comment]
In a previous project we have used CloudRail for facebook login and it was working fine, I have followed the same way of configuration when I created a new app for this project but I keep getting the same exception mentioned earlier. 
However, I have noticed something which might help you spot the problem, I tried to login again using the App ID and App Secret from the old project, I was able to login successfully "obtaining email and profile information", but reverting back to the new App ID and App Secret I got the Exception again.

The only difference between the two facebook apps is that in the Dashboard page the working app says "API Version 2.6" while the newer non-working one is "API Version 2.8" 

In my build.gradle I'm using: compile 'com.cloudrail:cloudrail-si-android:2.8.0'

I hope you can suggest a suitable fix soon enough as we are planning to release this project very soon and I'd like to use a unified social login method for all services.

**Comment by PatrickStoklasa** [comment]
If the SDK works with the credentials from your old app but not with the new ones that sounds like a configuration issue to me since the SDK is returning the correct result for your other app. The only thing i can suggest for now is to create another app and see if you get the same error message since i am not able to reproduce the error myself. Apart from that, as long as the app is still in development mode i could not even offer you to send me the app credentials via email and try it myself cause only the account who created the app is able to login. Unless you want to send me app credentials and your login information which is probably not the case.

**Comment by PatrickStoklasa** [comment]
We found the problem and we are working on a solution. We will push a fix this week!

**Comment by s-nour** [comment]
Thank you very much, I really appreciate it.

**Comment by PatrickStoklasa** [comment]
We just released the new version 2.8.1 which also contains the fix you are looking for. Let me know if this solves the issue.

**Comment by s-nour** [comment]
Hello there, 
Just tested with the new Facebook App and it's working. Thank you very much for your patience and help :)
