### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by kkrishnan90** [CloudRail/cloudrail-si-android-sdk#47]
Hey guys, 
I've been using cloud rail for some time and it's good and shaves a lot of time for developers by using a unified platform for all social logins. There are two queries that I have viz. 
1. The cloud rail website says the grade dependency version is 2.9.0 but on GitHub it says 2.8.2 being the latest. I'm a bit confused on this one. 
2. Do you guys maintain a change log for each version update ? That would help all the developers using your library to have a count of all the things that have changed over a period of time. 

Expecting a reply soon from the team. Thanks in advance and wishing you guys a great success.

**Comment by PatrickStoklasa** [comment]
Hey,

1. Where exactly did you find that 2.8.2 should be the latest version? Github contains the latest version 2.9.0, maybe we missed a spot to update the number.
2. The repository contains a changelog.txt which is being maintained.

**Comment by kkrishnan90** [comment]
Hey , 
1. I found the version mismatch inside your example project in the GitHub repo. Here's the link
https://github.com/CloudRail/cloudrail-si-android-sdk/blob/master/ExampleProjects/login-with-sample/frontend/LoginWithSample/app/build.gradle
2. Yes I got the change log here. 

I have another small query. Since your library uses Threads to communicate, how do I take the profile credentials of a user to the main thread where I have a couple of edit text inputs that needs to be filled after the login is done by the user. Can you help me on this too ?

**Comment by PatrickStoklasa** [comment]
The sample applications do not always run on the latest version if there weren't any improvements made that are relevant for the sample. But we plan to update the samples within the near future anyway.

What kind of profile credentials do you want to obtain?

**Comment by kkrishnan90** [comment]
Thanks ! 
I have currently integrated Facebook and Google login in my application loginpage along with some editText and imageview (where the users credentials like FullName, Email & PictureURL will be gained here and updated in this views once the user logs in).
Now when the user clicks on either of these two buttons, I start a thread as per the documentation to login the user. Once done, I have to get back to the login page and fill those editText values and imageview with users credentials. 
Hope you got my point ?

**Comment by PatrickStoklasa** [comment]
If i got it correctly, what you probably want to use is an [AsyncTask](https://developer.android.com/reference/android/os/AsyncTask.html). These make it very easy to propagate stuff that you do on a background thread back to the main thread. In your case, this could look sth. like that:

```java
public void loginUserAndShowProfileInfo() {
    // Starts a new task that performs login and displays profile info
    new GetProfileInfoTask().execute();
}

private class GetProfileInfoTask extends AsyncTask<Void, Void, ProfileInfo> {
    protected ProfileInfo doInBackground(Void... voids) {
        // This runs on background thread
        profile.login();

        ProfileInfo info = new ProfileInfo();
        info.setFullName(profile.getFullName());
        ...

        return info;
    }

    protected void onPostExecute(ProfileInfo info) {
        // This runs on the UI / Main Thread
        fullNameView.setText(info.getFullName());
       ...
    }
}
```

Obviously this is not runnable like that but should give you a basic idea of how you can handle these kind of situations. Is this what you were looking for?

**Comment by kkrishnan90** [comment]
Yup exactly the same ! Thanks ! I'll close this issue and reopen a new issue in case if this fails .
