### ISSUE TITLE
Box: getChildren delivers only 100 entries

### ISSUE THREAD

**Issue by wikirsch** [CloudRail/cloudrail-si-android-sdk#49]
I have a box folder with more than 100 entries (files/folders). Calling getChildren() returns only the first 100 entries. Is there any limit (if so, how can it be changed?). Used android sdk: 2.8.2.

**Comment by FlorianWendel** [comment]
Hi there,

thanks for reporting this. We’ve been told that a similar issue exists on GoogleDrive as well.
We’re currently working on fixing this, as well as a new pagination feature for folder children which will make it possible to load them in chunks for a better user experience.
I expect both to be released later this week or early next week.
All affected users will get a notification email.

**Comment by FlorianWendel** [comment]
This issue was fixed with the latest release, please reopen if it should persist for you.
