### ISSUE TITLE
Incomplete Metadata

### ISSUE THREAD

**Issue by wikirsch** [CloudRail/cloudrail-si-android-sdk#51]
Hi,
getModifiedAt() returns null for folders (at least for Dropbox and Box). Are there any plans to add this, since this information is kind of essential for sync tools?

**Comment by andredoubleu** [comment]
Hi, I'm experiencing the same problem, but only for Google Drive -- not for DropBox, Box, or OneDrive.

Sometimes I call cloudStorage.getChildren() and the resulting list of CloudMetaData objects will be correct, except each object has a modified date of null.  Likewise, if I call cloudStorage.getMetadata() it returns null.

However, the modified date isn't always null.  Usually after logging into Google Drive with CloudRail, the metadata will be returned correctly every time I request it for about a day, but then after that it will always returns null.  Clearing the data in my app seems to fix it (but obviously this isn't the optimal solution).

**Comment by FlorianWendel** [comment]
Hi there,

thanks for the info, we'll have a look at it and come back once we know more.

**Comment by andredoubleu** [comment]
Any update on the metadata returning null?  Are you having difficulty reproducing the issue?

**Comment by FlorianWendel** [comment]
Hi Andrew,
sorry for not getting back quicker.
We're currently extending the children retrieval functionality and hope to
get rid of the issue in the process. You can expect the new release this
week.

Am 21.11.2016 19:09 schrieb "Andrew" <notifications@github.com>:

**Comment by FlorianWendel** [comment]
The latest release brought fixes to getChildren and a new method to get children in chunks. Please check if this solves your issues.

**Comment by wikirsch** [comment]
Hi,
regarding the number of returned items getChildren() (as well as the new chunk method) is working as expected (at least for Box). Thus item #49 is done.
Regarding the problem with getModifiedAt() returning null for folders  (Box and Dropbox) the state from my point of view is like this:
Box:
Now returns a time also for folders but shows strange values - always exactly 17 hours in the past (for a folder created at 28.11.2016 9:06:13 I receive the modified at time 27.11.2016 16:06:13)
Dropbox:
getModifiedAt() still returns null for folders.

**Comment by FlorianWendel** [comment]
I found something with Box that might explain the oddity you describe. Which timezone are you in?

**Comment by FlorianWendel** [comment]
Either way, the Dropbox API does not provide the last modified date for folders. If you do need it, you might calculate it recursively as the maximum of its children but that can be a rather expensive operation which is also why we chose not to automatically do it.

**Comment by andredoubleu** [comment]
Florian,  I just got around to testing version 2.10.0.  It didn't exactly fix the error, but the nature of the error has changed.  Now, on my first time opening the app, I'm able to log into Google Drive and call getChildren() and it returns the correct results, but if I then close the app and reopen it, calling getChildren() no longer works (the call to getChildren() simply never returns.  I don't an exception or a timeout or anything really to indicate if the operation failed or not).   I'm calling getChildren() like so:

`List<CloudMetaData> cloudMetaDataList = cloudStorage.getChildren("/iDevices Connected");`

**Comment by FlorianWendel** [comment]
How do you go about saving and loading credentials? Or do you call getChildren on a just created instance of GoogleDrive?

**Comment by andredoubleu** [comment]
To save credentials I do:

`SharedPreferencesManager.putString(SHARED_PREFERENCES_FILE, GOOGLE_DRIVE, googleDrive.get().saveAsString());`

To load them later when I restart the app:

`String googleDriveString = SharedPreferencesManager.getString(SHARED_PREFERENCES_FILE, GOOGLE_DRIVE, null);

if(googleDriveString != null)
{
           googleDrive.get().loadAsString(googleDriveString);
}`

And in answer to your question: yes, after just creating my instance of Google Drive, I very soon after call googleDrive.getChildren().

**Comment by FlorianWendel** [comment]
Okay thanks, I believe I'm on to the problem.

**Comment by wikirsch** [comment]
Hi,
regrading returned value of getModifiedAt() for Box using latest sdk version (2.10.1):
The strange values with time offset of 17 hours are gone! That's fine.
But can you please check this: The returned time values now seems not to represent the time in UTC. A file/folder created at 9:05 CET returns 7:05 UTC (or 8:05 CET).

**Comment by FlorianWendel** [comment]
@wikirsch: When was the file created? Are you sure it is not CEST (summer time)?

**Comment by FlorianWendel** [comment]
@andredoubleu: The newest version fixes an issue with Google Drive reauthentication, does it fix your problem?

**Comment by wikirsch** [comment]
If assumption is correct that sdk should return time in UTC this value should not change if the local time zone is changed. Currently this seems not to be the case for Box and sdk 2.10.1.
For a certain file '1480940002000' (UTC: 05.12.2016 12:13:22) is returned if local time zone is WET (UTC). Changing the time zone to EET (UTC + 2) changes the returned value to  '1480932802000' (UTC: 05.12.2016 10:13:22).

**Comment by andredoubleu** [comment]
@FlorianWendel Just tried out version 2.11.0, but still whenever I call GoogleDrive.getChildren() the method never returns :(

**Comment by FlorianWendel** [comment]
@wikirsch: Looks like it has to do with how we parse Dates on Java/Android, I can reproduce it and I'm on it.
@andredoubleu: I can't seem to reproduce the issue you are having. Could you check if you can get our example to work? (https://github.com/CloudRail/cloudrail-si-android-sdk/tree/master/ExampleProjects/simple-cloud-file-manager)

**Comment by andredoubleu** [comment]
@FlorianWendel Sorry for the slow response.  I just got around to using your sample app today.  When I did so, I found that I was able to navigate through my personal Google Drive account perfectly EXCEPT for the 1 folder that I was having trouble accessing from my app that uses CloudRail.  In your sample app, when I clicked on the problem folder, the spinner would appear in the middle of the screen, and then spin endlessly.  Since I realized that that was the only folder that was acting funky in both your app and mine, I decided to manually delete that folder my Google Drive and then recreate it from my app.  Ever since then, Google Drive has worked perfectly in CloudRail.

I'm not sure exactly what was up with that folder, but everything seems to be working now.

**Comment by wikirsch** [comment]
Just to give some feedback: SDK version 2.12.0 fixes the problem with time zone of the returned time values for Box files and folders! This now works as expected.
Regarding the Dropbox API and the lack of providing the last modified date for folders: Are there any activities from your side to get this issue fixed (i.e. request improvement of the Dropbox API)?

**Comment by FlorianWendel** [comment]
That feature already seems to be requested (https://www.dropboxforum.com/t5/API-support/Find-the-last-updated-timestamp-of-a-directory-that-includes/m-p/166714, not from us). I can't tell if and when it will be implemented, maybe you can contact them directly.
