### ISSUE TITLE
isLoggedIn()

### ISSUE THREAD

**Issue by andredoubleu** [CloudRail/cloudrail-si-android-sdk#52]
Hi, I was wondering if there was a way with the CloudRail library to check if a user is currently logged in?

The app I'm building allows users to optionally backup their custom pictures to Google Drive, DropBox, OneDrive, or Box.  At certain points in the app, I initiate my sync process, uploading or downloading their custom pictures as needed.  But I don't want to initiate the sync process if the user isn't currently logged in.

I see a method called getUserLogin(), but if the user isn't logged in, the CloudRail library prompts the user to log in with a WebView (which I don't want -- I just want to know if they're logged in or not).  My solution to this problem was to use the explicit login() method at the point in my app where the user enables sycning, and once the login completed successfully, I would save a boolean indicating that they are logged in.  This solution has worked for me for a while now, but today I tried triggering my sync process (because my boolean indicated that I was logged in), but something must have happened b/c I was no longer authenticated with Box and the WebView kept popping up asking me to log in to my Box account.  If there was just a method called cloudStorage.isLoggedIn() or something like that that would really help me out!

Any ideas?

**Comment by PatrickStoklasa** [comment]
Hi Andrew,

There is currently no method to check that, but there are different ways to solve the issue. Usually what you want to do after a user logged in the first time is to call saveAsString() and persist the string returned by the method (for instance using the SharedPreferences). What this method returns, is a stringified JSON object which contains the authentication credentials such as access token, refresh token and the like. Now you can check if this data is available and if so load it into the service by calling loadAsString(). After that you can continue as usual and you know that the user was logged in.

If you don't want to persist the data you could also just call saveAsString() and check if the returned String is an empty JSON object like "{}". If so, the user is not logged in.

Let me know if this solves your issue.

**Comment by andredoubleu** [comment]
Thanks for the quick response.  I'll give this a try and let you know of the results/

**Comment by andredoubleu** [comment]
It seems like the method you suggested has been working pretty reliably for the last 2 days -- thanks!
