### ISSUE TITLE
HttpException if user logs in multiple networks with AdvancedAuthentication

### ISSUE THREAD

**Issue by Unbekannter** [CloudRail/cloudrail-si-android-sdk#55]
Hi,

if user logs in multiple networks with the AdvancedAuthentication there are some errors.
If this is the first login, while the app runs, all is perfect. But if the user want's to login in an another Social Network (after the first sucessfully login), some different errors are coming.

At Facebook login:

> System.err: com.cloudrail.si.exceptions.HttpException: {"error":{"message":"Invalid verification code format.","type":"OAuthException","code":100,"fbtrace_id":"placeholder"}}
> System.err:     at com.cloudrail.si.services.Facebook.getFullName(Facebook.java:479)
> System.err:     at placeholder $16$1.doAsync(SettingsFragment.java:1174)
> System.err:     at placeholder $16$1.doAsync(SettingsFragment.java:1170)
> System.err:     at com.arasthel.asyncjob.AsyncJob$4.run(AsyncJob.java:91)
> System.err:     at java.lang.Thread.run(Thread.java:818)

At Twitter login (also MS Live):

> System.err: java.lang.RuntimeException: ServiceCode Error in function authenticate at 32
> System.err:     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:111)
> System.err:     at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
> System.err:     at com.cloudrail.si.services.Twitter.getFullName(Twitter.java:731)
> System.err:     at placeholder $18$1.doAsync(SettingsFragment.java:1335)
> System.err:     at  placeholder $18$1.doAsync(SettingsFragment.java:1331)
> System.err:     at com.arasthel.asyncjob.AsyncJob$4.run(AsyncJob.java:91)
> System.err:     at java.lang.Thread.run(Thread.java:818)
> System.err: Caused by: java.lang.IndexOutOfBoundsException
> System.err:     at com.cloudrail.si.servicecode.Sandbox.getEntry(Sandbox.java:217)
> System.err:     at com.cloudrail.si.servicecode.Sandbox.getVariable(Sandbox.java:282)
> System.err:     at com.cloudrail.si.servicecode.Sandbox.getVariable(Sandbox.java:249)
> System.err:     at com.cloudrail.si.servicecode.commands.Set.execute(Set.java:35)
> System.err:     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
> System.err: 	... 6 more

At Instagram also LinkedIn:

> System.err: com.cloudrail.si.exceptions.HttpException: Matching code was not found or was already used.
> System.err:     at com.cloudrail.si.services.Instagram.getPictureURL(Instagram.java:531)
> System.err:     at  placeholder$19$1.doAsync(SettingsFragment.java:1412)
> System.err:     at  placeholder$19$1.doAsync(SettingsFragment.java:1408)
> System.err:     at com.arasthel.asyncjob.AsyncJob$4.run(AsyncJob.java:91)
> System.err:     at java.lang.Thread.run(Thread.java:818)

At GitHub:

> System.err: java.lang.RuntimeException: ServiceCode Error in function makeHTTPRequest at 4
System.err:     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:111)
System.err:     at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
System.err:     at com.cloudrail.si.services.GitHub.getFullName(GitHub.java:325)
System.err:     at  placeholder$23$1.doAsync(SettingsFragment.java:1639)
System.err:     at  placeholder$23$1.doAsync(SettingsFragment.java:1634)
System.err:     at com.arasthel.asyncjob.AsyncJob$4.run(AsyncJob.java:91)
System.err:     at java.lang.Thread.run(Thread.java:818)
System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
System.err:     at com.cloudrail.si.servicecode.commands.string.Concat.execute(Concat.java:41)
System.err:     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
System.err: 	... 6 more

At Slack:

> System.err: com.cloudrail.si.exceptions.HttpException: invalid_code
> System.err:     at com.cloudrail.si.services.Slack.getFullName(Slack.java:303)
> System.err:     at  placeholder$26$1.doAsync(SettingsFragment.java:1849)
> System.err:     at  placeholder$26$1.doAsync(SettingsFragment.java:1843)
> System.err:     at com.arasthel.asyncjob.AsyncJob$4.run(AsyncJob.java:91)
> System.err:     at java.lang.Thread.run(Thread.java:818)

I'am using 2.14.1 at SdkVersion 25

Furthermore: If AdvancedAuthentication is turned off, it still works.

Greets

**Comment by FlorianWendel** [comment]
Hi there, thanks for reporting.
Looks like something isn't properly cleared in the SDK...
We'll look into it and come back to you once it's fixed.

**Comment by PatrickStoklasa** [comment]
We just published a new version containing a fix. Please let me know if you still experience any issues.

**Comment by leijdekkers** [comment]
I am facing a similar issue when i use the advanced authentication example and try to logout. So i added a logout button to the sample app and the code looks like this .

 private class Logout implements View.OnClickListener {
        @Override
        public void onClick(View v)
        {
            SharedPreferences sharedPreferences = getPreferences(Context.MODE_PRIVATE);
            SharedPreferences.Editor editor = sharedPreferences.edit();
            editor.putBoolean(LOGIN_PENDING, false);
            editor.remove(AUTH_DATA);
            editor.apply();

            // Start the logout process
            new Thread() {
                @Override
                public void run()
                {
                    cs.logout();
                }
            }.start();
        }
    }


When i Login the first time it is all okay. But when i Logout and then do a Login agin i get this error:(a HTTPException)

E/AndroidRuntime: FATAL EXCEPTION: Thread-18414
Process: com.cloudrail.advancedauthentication, PID: 30970
  com.cloudrail.si.exceptions.HttpException
                                                       at com.cloudrail.si.services.GoogleDrive.login(GoogleDrive.java:1478)
                                                       at com.cloudrail.advancedauthentication.MainActivity$StartLogin$1.run(MainActivity.java:106)
