### ISSUE TITLE
Google Drive Upload: Filesize 0 byte

### ISSUE THREAD

**Issue by develuxe** [CloudRail/cloudrail-si-android-sdk#56]
Hello!
I'm trying to upload a sqlite databse to google drive.
I can create folder and upload my database but the filesize is 0 bytes after uploading. I'm sure im missing something (new to java/android development).

This is how I upload the database
```
private void upload(Context mContext) {
        CloudRail.setAppKey("APIKEY");
        final GoogleDrive cs = new GoogleDrive(mContext, "XXX", "", "XXXt", "XXX"); // remember to follow the instructions from step 2 for authentication
        cs.useAdvancedAuthentication();

        new Thread() {
            @Override
            public void run() {
                InputStream stream = null;
                try {
                    if (!cs.exists("/Foldername")) {
                        cs.createFolder("/Foldername");
                        Log.i("info", "Folder successfully created");
                    }
                    File dbFile = getApplicationContext().getDatabasePath("rezepte.db");
                    stream = new FileInputStream(dbFile);
                    ByteArrayOutputStream os = new ByteArrayOutputStream();
                    int b;
                    while ((b = stream.read()) != -1)
                        os.write(b);
                    long size = os.size();
                    os.flush();
                    os.close();

                    cs.upload("/Foldername/Test.db", stream, size, false);
                    Log.i("info", "File successfully uploaded");
                } catch (Exception e) {
                    // TODO: handle errors
                    Log.i("error", e.getMessage());
                } finally {
                    // TODO: close stream
                }
            }
        }.start();
    }
```

Thank you!

**Comment by FlorianWendel** [comment]
Hi there,

it looks like you're dumping the InputStream that points to the DB into an OutputStream which you only use to get the size. That's not the right way to do it though, after reading the InputStream completely once it will be empty so you're not actually sending any data when you pass the now empty stream to the upload() method. Moreover, calling size() on the OutputStream won't reliably return the file size.

Try something like this instead:

    File dbFile = getApplicationContext().getDatabasePath("rezepte.db");
    stream = new FileInputStream(dbFile);             
    long size = dbFile.length();                  
    cs.upload("/Foldername/Test.db", stream, size, false);

I haven't run the code so tell me if this works for you.

**Comment by develuxe** [comment]
Thank you, Florian!
How did I miss that...

Grüße von Koblenz nach Mannheim ;)
