### ISSUE TITLE
Example Retrieve Shared folders/file for Google Drive

### ISSUE THREAD

**Issue by leijdekkers** [CloudRail/cloudrail-si-android-sdk#58]
Trying to get 'shared' folders and files for Google Drive using the advanced request. Using the Dropbox example i tried the following code. The query for Google Drive should be something like this "/files?q=sharedWithMe+%3D+true".

However the response does not give the shared folders or files. Any idea what is wrong?

 AdvancedRequestSpecification req = new AdvancedRequestSpecification("/files?q=sharedWithMe+%3D+true");

            // Set the HTTP request method to POST
            req.setMethod("POST");

            // Specify the body and let it be converted to JSON
            Map<String, Object> body = new HashMap<>();
            body.put("limit", 100);
            req.setBodyStringifyJson(body);

            // Specify the headers
            Map<String, String> headers = new HashMap<String, String>();
            headers.put("Content-Type", "application/json");
            req.setHeaders(headers);

            // Execute the request, CloudRail will start the authentication flow if necessary and append the authorization header.
            // The response is checked for errors.
            AdvancedRequestResponse res = mCloudStorage.advancedRequest(req);

            // Extract the parsed response body
            Map<String, Object> parsed = (Map<String, Object>) res.getBodyJsonParsed();

            // Now you can work with the answer
            List<Map<String, Object>> entries = (List<Map<String, Object>>) parsed.get("kind");
            Log.i("info", "We have " + entries.size() + " shared files");

**Comment by FlorianWendel** [comment]
Hi there,

it looks like you'll have to modify the example some more to get it working.
I'm following https://developers.google.com/drive/v3/reference/files/list for this assuming that this is the endpoint you want to use.
First, the request method needs to be GET instead of POST, no body is needed and you needn't specify the Content-Type header since you're not sending a body. The "kind" key of the response also seems to be a string and you will need to cast appropriately.

**Comment by PatrickStoklasa** [comment]
As discussed in our email I quickly tried this myself and the following request worked fine for me:

    AdvancedRequestSpecification spec = new AdvancedRequestSpecification("/files?q=sharedWithMe+%3D+true");
    spec.setMethod("GET");
    AdvancedRequestResponse res = mCloudStorage.advancedRequest(spec);
    Log.d("advancedRequest", res.getBodyAsString());`

**Comment by FlorianWendel** [comment]
Awesome Patrick!
I think in this case you don't even need to specify the method since GET is the default anyway which saves another line of code ;)

**Comment by leijdekkers** [comment]
Confirmed! works like a charm. Here is the code to see the shared folders/files when you parse it.

Thanks!

```
 AdvancedRequestSpecification req = new AdvancedRequestSpecification("/files?q=sharedWithMe+%3D+true");
            AdvancedRequestResponse res = mCloudStorage.advancedRequest(req);

            // Extract the parsed response body
            Map<String, Object> parsed = (Map<String, Object>) res.getBodyJsonParsed();

            // Now you can work with the answer
            List<Map<String, Object>> entries = (List<Map<String, Object>>) parsed.get("files");
            Log.i("info", "We have " + entries.size() + " shared folders/files");
```
