### ISSUE TITLE
 White spaces in folder path not handling: getChildren(String folderPath)

### ISSUE THREAD

**Issue by leijdekkers** [CloudRail/cloudrail-si-android-sdk#59]
I am using Google Drive and when I execute this line of code to get the files in a subfolder, it does not work if there are white spaces in the currentPath string.

  **List<CloudMetaData> items = getService().getChildren(currentPath);**

For example
currentPath = /test1/sub folder

This will crash the app.
I tried to replace the white space with %20 but no luck.

Would be nice to browse folders that have a white space in them!

**Comment by FlorianWendel** [comment]
How does the app crash, is there a specific exception?

I've just rerun our tests and they cover many scenarios with paths containing spaces (no %20 needed) and they all pass. We've also checked with our example app "simple cloud file manager" and it navigates into folders with spaces without problems.

Are you using the latest SDK version?
Does the folder exist?
If it doesn't, a NotFound Exception would be thrown which should be caught and handled.

**Comment by leijdekkers** [comment]
Hi

Tested here again with the "simple-cloud-file-manager" app. So the app craches if you have for example a topfolder with a space in it. In my case "Spring 2014" When i tap on the top folder it works when you have a space. Then inside the "spring 2014" i have another folder called  "week 8". When i Tap on that folder the app crashes with the following error. 

```
com.cloudrail.si.exceptions.NotFoundException: Specified file does not exist.
at com.cloudrail.si.services.GoogleDrive.getMetadata(GoogleDrive.java:1414)
at com.cloudrail.fileviewer.Files$1$1.run(Files.java:174)
at java.lang.Thread.run(Thread.java:818)
```

Please try it for yourself.

**Comment by PatrickStoklasa** [comment]
Hi,

I just created the same folder structure with these two folders and I'm able to navigate into the second one without issues. Could you maybe create a similar structure within your drive again and see if it works. If so the issue might be a specific file / file extension that causes problems. But without knowing the exact file tree I can't really give you more information.
