### ISSUE TITLE
How to download a shared file in Google Drive?

### ISSUE THREAD

**Issue by leijdekkers** [CloudRail/cloudrail-si-android-sdk#60]
I would like to download a **shared** file using Google drive. I used this to get the file for the Google Drive File

            String url = String.format("/files/%1$s?alt=media", "0B9jNhSvVjoIVM3dFcFCFKRmVIOVU");
            AdvancedRequestSpecification req = new AdvancedRequestSpecification(url);
            AdvancedRequestResponse res = mCloudStorage.advancedRequest(req);**

But how to proceed to actually read the file as InputStream?

So this does not work obviously using the build in method of CloudRail
// InputStream data = mCloudStorage.download("0B9jNhSvVjoIVM3dFcFCFKRmVIOVU");

**Comment by FlorianWendel** [comment]
If the response of that request is the file itself you should be able to read it by calling getBodyAsStream() on the AdvancedRequestResponse object and get an InputStream.
