### ISSUE TITLE
Advanced Authentication - "Open with" Dialog not shown

### ISSUE THREAD

**Issue by Unbekannter** [CloudRail/cloudrail-si-android-sdk#61]
Good evening,

i have a problem but i dont know if this is an bug of CloudRail - if not -> Sorry :)

When i use the Advanced Authentication, the user normally gets the Dialog "Open With" after a successfully login - but if the user click on the wrong kind (like open with web browser) - this setting will saved and so the dialog wont show twice. So he get's an Error like:
"Website not available"

Is there any solution to show the "Open with" dialog at any time if the user logs in successfully?

AndroidManifest:
```
<intent-filter android:autoVerify="true">
<data android:host="www.cloudrailauth.com" android:scheme="https" android:path="/auth" />
<action android:name="android.intent.action.VIEW" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />
</intent-filter>
```

Greets

**Comment by PatrickStoklasa** [comment]
If a user selects the browser to open the authentication page and also makes it the standard, there is not much we can do about that. But we have stumbled upon that issue ourselves and have made some adjustments that should enable you to fix it. First and foremost you can use custom url schemes which would look sth like that: 'your.app.package:/oauth2redirect'. By using these the browser won't even be an option to choose from. This is how you can setup one for [GoogleDrive](https://documentation.cloudrail.com/android/android/Services#google-drive). I would also encourage you to take another look at our [cloud storage sample](https://github.com/CloudRail/cloudrail-si-android-sdk/tree/master/ExampleProjects/simple-cloud-file-manager) which has been updated recently as well as this [blog article](https://cloudrail.com/solving-disallowed_useragent-for-google-services/). Please let me know if you had success or if you have more questions.

**Comment by Unbekannter** [comment]
Okay thats sounds good. But how can I use it with the Facebook Login?
Facebook doesn't accept URI-Schemes like packagename/oauth2redirect
It will be automatic converted to http://packagename/oauth2redirect

Is there any solution for this?

Greets

**Comment by PatrickStoklasa** [comment]
If a provider doesn't allow this kind of authentication there is nothing we can do and you would need to use the standard WebView to do the authentication. As far as I know, the native Facebook SDK uses WebViews as well and thus no custom schemes.

**Comment by Unbekannter** [comment]
I have found a solution for this problem, if any other have this problem:
-Set the callback URL as a real website, which can show the user, that he wasn't correctly redirected to your app
-Add a clickable link, button or etc. which will catch the auth code and will start the app with the uri packagename:/oauth2redirect from your website

Thanks to CloudRail
