### ISSUE TITLE
Login Issue at MS Live Social Login

### ISSUE THREAD

**Issue by Unbekannter** [CloudRail/cloudrail-si-android-sdk#62]
Hello,

it seems that the last update has crashed the MS Live Login.
All keys and secrets are correct, all is done like your wiki.
Furthermore the same code has worked before.

I'am only requesting user name and user id.

> W/System.err: java.lang.RuntimeException: ServiceCode Error in function authenticate at 4
> W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference

Best greets

**Comment by PatrickStoklasa** [comment]
Hi there,

I quickly tested it with my own account but I don't have trouble with the current version. Are you using the standard authentication or the advanced version?

**Comment by PatrickStoklasa** [comment]
Still this works for me as well. It appears that in your case the URL you are passing to the SDK through the received Intent does not have a "code" key within it's query. Could you maybe check the Intent before passing it to the SDK by printing the URI returned by getData()?

**Comment by Unbekannter** [comment]
Thank you for the tipp, with getData().
It seems that MS Live need a redirect URI with SSL.

> The provided value for the input parameter 'redirect_uri' is not valid. The scope 'wl.emails wl.birthday' requires that the request must be sent over a secure connection using SSL
