### ISSUE TITLE
CloudRail asks for unwanted permissions

### ISSUE THREAD

**Issue by aleksandarmilutinovic** [CloudRail/cloudrail-si-android-sdk#67]
When I start my auth process with Facebook, it shows me the following error:
![fb_err](https://cloud.githubusercontent.com/assets/12120923/24840475/247cf874-1d6e-11e7-932d-dcf2b2cbafd7.png)

I really just want for my users to authentificate with Facebook, and not my app to post on their behalf at all. I never set up permissions I need, and never used any function that posts something to Facebook.

How can I avoid this screen from showing?

**Comment by PatrickStoklasa** [comment]
Hi there,

By default the SDK requests all the permissions that someone might need to perform all the actions provided by our SDK. You can specify the permissions you need by adding another constructor parameter that represents the scopes. This expects a List<String> and the permissions you are looking for should be 'public_profile' and 'email'.

**Comment by donpwilson** [comment]
I, too, was  facing the same issue. I followed the suggestion above and it works perfectly. I added the following to my Facebook constructor:

```javaScript
                    List<String> scope = new ArrayList<>();
                    scope.add("publish_actions");
                    scope.add("public_profile");
                    final Facebook facebook = new Facebook(My_Application_Base.getInstance().getApplicationContext(),
                            Get.GetString(R.string.facebook_app_id), Get.GetString(R.string.facebook_secret),scope);
`
