### ISSUE TITLE
How to post multiple images in Social

### ISSUE THREAD

**Issue by jiemizc** [CloudRail/cloudrail-si-android-sdk#72]
Hi, a very quick question, how to upload multiple images in one post using cloudrail?

**Comment by PatrickStoklasa** [comment]
This is not yet part of our unified interface but it sounds to me like a good extension. I will see if it fits anywhere in our roadmap. Until then, you could still utilize our advanced request feature to do this. Not as comfortable but you still save doing the authentication. 
Here is a link to the documentation: https://documentation.cloudrail.com/android/android/Usage#advanced-request
