### ISSUE TITLE
Remove supportsRtl from AndroidManifest

### ISSUE THREAD

**Issue by jaredrummler** [CloudRail/cloudrail-si-android-sdk#74]
There is a manifest merge conflict if the app defines `supportsRtl` in the AndroidManifest.

> Error:Execution failed for task ':app:processDebugManifest'.
>  Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:12:7-34
>   	is also present at [com.cloudrail:cloudrail-si-android:2.17.0] AndroidManifest.xml:16:9-35 value=(true).
>   	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:7:3-133:17 to override.

This should be removed from the AAR in my opinion and defined by the app.

**Comment by PatrickStoklasa** [comment]
You are right, it doesn't need to be in there. I will make sure it will be removed in the next release. Thanks for letting us know!
