### ISSUE TITLE
Multiple cloud storage accounts in single app

### ISSUE THREAD

**Issue by jaredrummler** [CloudRail/cloudrail-si-android-sdk#75]
How can I have multiple accounts for a cloud storage? 

**Reproduction Steps:**

Create a new app and login to a cloud storage in `onCreate`:

```java
@Override protected void onCreate(Bundle savedInstanceState) {

  ...

  CloudRail.setAppKey(MY_CLOUDRAIL_LICENSE_KEY);
  final Dropbox dropbox = new Dropbox(this, MY_DROPBOX_KEY, MY_DROPBOX_SECRET);
  new Thread(new Runnable() {
    @Override public void run() {
      System.out.println(dropbox.getUserLogin());
    }
  }).start();
}
```

**Actual Behavior:**

CloudRail requests to login the first time only. If the app is launched a second time the previous username is printed.

**Expected behavior:**

Dropbox should ask for a new login each time the app is launched. I would expect to only auto-login when using `CloudStorage#saveAsString()` and `CloudStorage#loadAsString(String persistent)`.

**Comment by PatrickStoklasa** [comment]
What probably happens is that the WebView used for authentication keeps the user logged in through cookies and thus Dropbox automatically confirms the app without prompting the user to login again. Take a look at our FAQ, this should help you solve the issue: 
https://documentation.cloudrail.com/android/android/FAQ#when-using-the-logout-method-of-a-service-and-then-login-again-it-doesn-t-seem-to-have-logged-out-properly-is-there-a-way-to-fix-that

**Comment by jaredrummler** [comment]
Thanks. Adding

```java
CookieManager.getInstance().removeAllCookies(null);
CookieManager.getInstance().flush();
```

before `login()` worked.
