### ISSUE TITLE
Facebook profile no method found

### ISSUE THREAD

**Issue by kkrishnan90** [CloudRail/cloudrail-si-android-sdk#8]
Hi,
Thanks for such an amazing library that shaves tons of time for developers like us to implement social logins.
I can see the profiles stating a new method for GooglePlus,LinkedIn etc. , but when I create a new profile for Facebook, it says Facebook method not found in Android Studio. Kindly request you to update on this.

**Comment by FlorianWendel** [comment]
Hi there,
thanks a lot for your positive feedback!

Can you tell me what you did to include the library and show the code you use to connect to Facebook with CloudRail?

**Comment by kkrishnan90** [comment]
Sure ! 
Here it is, 
Step 1 : Added the Gradle dependencies along with maven url . 
Maven URL added to root level build file 
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.google.gms:google-services:1.5.0-beta2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "http://maven.cloudrail.com"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
Then here it is , my app level build.gradle file
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "cabdigital.socialloginsample"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.google.android.gms:play-services-auth:9.0.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.facebook.android:facebook-android-sdk:4.0.0'
    compile 'com.cloudrail:cloudrail-si-android:2.0.1'
}`


Then in my MainActivity.class, I have invoked the methods like this,

`import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.widget.Button;

import com.cloudrail.si.interfaces.CloudStorage;
import com.cloudrail.si.interfaces.Profile;
import com.cloudrail.si.services.GooglePlus;
import com.pst.cabdigital.R;

/**
 * Created by krishnankumar on 26/05/16.
 */
public class MainActivity extends AppCompatActivity {
    Button fbButton;
    CloudStorage cs;
    Profile profile;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        fbButton=(Button)findViewById(R.id.fbButton);

        profile=new Facebook() //Method not supported and highlighted in red colour in Android Studio.
    }
}
`

Request your help to fix this.

**Comment by FlorianWendel** [comment]
It looks like you're using version 2.0.1. 
Try using 2.1.0 which is the latest version. 
This is the version where all the profile services were added, though the interface might have already been there in version 2.0.1.

**Comment by kkrishnan90** [comment]
Silly me ! Fantastic ! Thanks a ton Florian ! Got it working now ! Once again a huge thanks to the entire team for creating such an amazing library again ! And one more small query Florian, how do we get the profile to logout from a different page .. I mean the login and logout happens in different page. Should I have to pass the profile object to the screen I'm gonna logout ?

**Comment by FlorianWendel** [comment]
Yes, that would be a good way to do it. The object keeps the authentication state so login and logout should happen on the same object.

**Comment by kkrishnan90** [comment]
Sure thanks a bunch for your immediate response and support Florian. Appreciate it ! I'm closing this issue as you've promptly given me a solution to fix it.
