### ISSUE TITLE
Box asks for username and password every time

### ISSUE THREAD

**Issue by clintidau** [CloudRail/cloudrail-si-android-sdk#81]
I have successfully used Cloudrail in my Android app to upload files to Dropbox, Onedrive, and Box. Dropbox and Onedrive only ask me to log in the first time, but Box asks for username and password every time I start a new Cloudrail "Box" object.

**Comment by PatrickStoklasa** [comment]
The authentication for the other services is probably triggered as well but these services allow a user to stay logged in so they do not need to enter their credentials every time. What you can do though for all of the services is to use saveAsString() and loadAsString(). After the login was performed successfully you can call saveAsString() and persist the returned string, for instance using SharedPreferences. Whenever you want to reinitialize a service you can call loadAsString() passing the string you acquired previously before making any call to the SDK. This will generally skip the authentication if the contained credentials are still valid.

**Comment by clintidau** [comment]
Thanks, saveAsString and loadAsString works perfectly.
