### ISSUE TITLE
Documentation is bad for GoogleDrive

### ISSUE THREAD

**Issue by clintidau** [CloudRail/cloudrail-si-android-sdk#82]
First I followed the code examples on Cloudrail website, where it told me I need a "client identifier" and "client secret" for GoogleDrive. Google does not provide a client secret. After lots of searching I found the code example on the Cloudrail Github page says to leave the string blank instead, which works. Then I encountered the ‘disallowed_useragent’ error and I tried to follow instructions from your blog https://blog.cloudrail.com/solving-disallowed_useragent-for-google-services/ but I don't know what to use for "YourRedirectURI". Nothing I try here will return the token to my app. If I use the "oob" string from my GoogleDrive json file I get a token with instructions to copy and paste it into my app, but I don't think that's what I want.
It was easy to use Cloudrail for Dropbox, Onedrive, and Box. It shouldn't be this complicated to use GoogleDrive.

**Comment by PatrickStoklasa** [comment]
Thanks for your feedback on our documentation! We will improve it where possible.

The redirect uri you use always consists of you package name and a path chosen by you. So if your package name would be 'com.sample.testapp' you could for instance choose a redirect uri like this: 'com.sample.testapp:/authentication_redirect'.

**Comment by dchris87** [comment]
@clintidau Did you figure out the redirect uri thing? Anything I put in there other then the oob string from my JSON file gives a "Error: redirect_uri_mismatch" error. The solution given by @PatrickStoklasa doesn't work either and throws the same error. I think theres more to his answer thats needed for this to work. Besides there needs to be a clear explanation about the redirect_uri. I agree with @clintidau The documentation is worst for this service which portrays itself as the unified cloud storage option...etc.

**Comment by PatrickStoklasa** [comment]
Hey Chris,

I appreciate that you are using our solution. We are aware that the authentication for Google is not as easy as for the others. Unfortunately we can not tell Google that they should do it like everyone else does but we are here to make sure that you get it working. 

Could you please walk me through the steps you took to setup the authentication for Google? Maybe you can provide some of your code as well since this would make it easier for me to locate the issue.

**Comment by dchris87** [comment]
Thanks you for your response @PatrickStoklasa . I understand that Google has made this quiet difficult. But I expected CloudRail to be more detailed in explaining the issue and setup. As mentioned by @clintidau the CLIENT_SECRET field doesn't even apply to Google Drive, but the documentation provided on the official website of yours has not even explained this. My suggestion is to explain this and also give more details on how/where to get the redirectUri field. Besides this, the library version provided on the official website is not updated. Please look into it...make your documentation synchronized on the website and Github. Or just use one place where the entire documentation is listed. Currently Google Drive users have to toggle jump for clear explanations on GitHub, the CloudRail website and the old documentation that was available some time ago on the website. This is clearly bad for your business as like me many will just not invest time in implementing CloudRail for Google Drive.

Here's my code in my HomeActivity: 

        CloudRail.setAppKey([Cloudrail Api KEY]);
        CloudRail.setAdvancedAuthenticationMode(true);

        GoogleDrive service = new GoogleDrive(
                this,
                "[My Drive Android API Key]",
                "",
                "org.swiftapps.swiftbackup:/authentication_redirect",
                "drive_state"
        );

        Util.threadedAction(new Util.ThreadListener() {
            @Override public void inBackground() {
                service.login();
            }

            @Override public void postBackground(long l) {
                Util.shortToast(activity,"Login Thread over?");
            }
        });

In Android Manifest, added the intent filter in the concerned activity tags:

        <activity
            android:name=".home.HomeActivity"
            android:label="@string/app_name"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:theme="@style/ThemeSplash">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="org.swiftapps.swiftbackup" />
            </intent-filter>
        </activity>

Below is the error in the browser:

![untitled-1](https://user-images.githubusercontent.com/6801896/28469104-c84264a0-6e52-11e7-9955-22b75f34181f.png)

**Comment by PatrickStoklasa** [comment]
You are totally right, the documentation needs to be better and more consistent in that regard. We are currently working on that. 

Regarding your issue, the code you pasted looks fine to me and I'm pretty much doing the same thing in my test case. I use 'com.cloudrail.si.testapp:/authentication_redirect' as my redirect URI and it works fine. Here is my configuration on the Google Developer Console as a reference:

<img width="651" alt="bildschirmfoto 2017-07-24 um 15 34 06" src="https://user-images.githubusercontent.com/8956370/28525996-6370a5e2-7086-11e7-9be4-3aafd8e269e7.png">

If the error is thrown like that, the issue should be somewhere in the configuration. Maybe try to recreate your Android App in the developers console and see if the new one works.
