### ISSUE TITLE
Documentation for "search" function in CloudStorage interface

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#84]
I note that you have recently included a search function. However I cannot find anything to show how to use it and, specifically, how to set up the query parameters. Could you possibly point me in the right direction. Can it be used to filter what is returned by getChildren and getChildrenPage? I would like to use it for all of Google Drive, OneDrive, Box and Dropbox .

**Comment by PatrickStoklasa** [comment]
The main documentation can be found here https://cloudrail.com/integrations/interfaces/CloudStorage;interfaceId=CloudStorage;interfaceFunctionId=CloudStorage-search. The query parameter is basically just a search string that will be matched against file names.

**Comment by donpwilson** [comment]
Thanks, I had found that documentation. Including an example or explanation like you've given above would help, I think. I've tried it out  to find "jpg" files (on Google Drive) and can confirm that it worked. However, it doesn't meet my desire for a filter. It was slow, not totally surprisingly, compared to getChildren and GetChildrenPage and is case sensitive - I'd also need to search for "JPG".
