### ISSUE TITLE
Google Drive - ServiceCode Error in function getFolderContent at 3

### ISSUE THREAD

**Issue by pliratu** [CloudRail/cloudrail-si-android-sdk#85]
When using advanced authentication mode on Google Drive I get following exception when I try to list files and folders:

`W/System.err: java.lang.RuntimeException: ServiceCode Error in function getFolderContent at 3
W/System.err:     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:111)
W/System.err:     at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
W/System.err:     at com.cloudrail.si.services.GoogleDrive.getChildren(GoogleDrive.java:1524)
W/System.err:     at com.appgenix.bizcal.ui.AttachmentActivity$1.run(AttachmentActivity.java:325)
W/System.err:     at java.lang.Thread.run(Thread.java:776)
W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 
'java.lang.String java.lang.Object.toString()' on a null object reference
W/System.err:     at com.cloudrail.si.servicecode.commands.string.Concat.execute(Concat.java:41)
W/System.err:     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
W/System.err: 	... 4 more`

However, when I logout and login several times the issue disappears. Other features like createFolder are working as intended. I don't change the content during the test, so the files and folders on Google Drive keep the same. Its somehow a very big problem cause a potential user can not use this feature.

Using com.cloudrail:cloudrail-si-android:2.18.0.

**Comment by PatrickStoklasa** [comment]
Are you always trying this with the same path? When I look into the code, the line that seems to cause the issue is missing a correct folder id for the given path. This in turn means that our attempt to locate the path which you are passing to the SDK does not complete successfully.
I have not been able to reproduce this so far. It would be great if you can give me some more information the paths you are testing. Maybe there is a special character in one of them which we are unable to process.

**Comment by pliratu** [comment]
*Are you always trying this with the same path? *: No, I tried different pathes, started with root "/" and some test folders.

*It would be great if you can give me some more information the paths you are testing. Maybe there is a special character in one of them which we are unable to process.*: No matter which Google Account I try, it is always the same issue. I tested it with more than 10 Google Accounts, always the same error.

`List<CloudMetaData> items = Services.getInstance().getService(serviceId).getChildren(currentPath);`

where serviceId is GoogleDrive and currentPath is "/" or other test folder.

After some time (5-20 minutes), all works flawless and I really changed **nothing**. It occurs also on complete empty GoogleDrive Accounts (no folders, no files).

**Comment by PatrickStoklasa** [comment]
I still can not reproduce it... Could you maybe setup a separate project and try if you experience the same there. If so, you can send me that project and I can try to debug it there.

**Comment by pliratu** [comment]
After a lot of research I detected the problem: I'm switching between activities, so I did it not like in the tutorial. However, I found some more issues, but I will open them separately.

**Comment by PatrickStoklasa** [comment]
Ok, sure! Glad you got it working.
