### ISSUE TITLE
Google Drive Advanced Auth intent.getCategories() null

### ISSUE THREAD

**Issue by p0087** [CloudRail/cloudrail-si-android-sdk#92]
I refer to your advanced auth tutorials/sample code for Google Drive. Using Chrome on Android, everything works as per expected. Using Firefox on Android (possibly other browsers?), `intent.getCategories()` is null when receiving `onNewIntent(Intent intent)`

**Comment by PatrickStoklasa** [comment]
I see. This might actually be different for some browsers. In that case and if you do not handle other Intents in your application you can also remove the check. If you do or if you just want to make sure that the Intent is correct you can always evaluate the URL from Intent.getData() if I'm not mistaken.

**Comment by p0087** [comment]
Yeah I think `intent.getData().getPath()` matching `/oauth2redirect` should be sufficient. Just might wanna update the docs

**Comment by PatrickStoklasa** [comment]
I agree. We will update the samples as soon as possible. Thanks for bringing that up!
