### ISSUE TITLE
Cloudrail saveAsString only returns [{}] as persistable.

### ISSUE THREAD

**Issue by LukasAnda** [CloudRail/cloudrail-si-android-sdk#93]
Hi, when I call saveAsString on any cloudrail service, it returns only [{}] as persistable, why ?

**Comment by PatrickStoklasa** [comment]
Hi there,

this is the result when the user has not logged in yet. You need to either call login() or any other method of the SDK first to obtain a correct value from saveAsString(). 
In case you did that, the issue might be that the instance you are calling this on is not the same as the one that has performed the login before. Try to call saveAsString() immediately after login() or whichever method triggers the authentication.

**Comment by LukasAnda** [comment]
Hi, thanks, now I've fixed my implementation and everything works fine ^_^ thanks
