### ISSUE TITLE
Open files without downloading them 

### ISSUE THREAD

**Issue by LukasAnda** [CloudRail/cloudrail-si-android-sdk#95]
Hi, is there a way to "download" the file -> e,g, get its input stream and then just pass the input stream to ParcelFileDescriptor ?

**Comment by PatrickStoklasa** [comment]
The download() method returns the input stream while the file is still being transferred so you should be able to use it in the way you intend to use it. We are using streams internally so the file is not yet fully downloaded when the stream is returned.
